/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cfp;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Random;
import java.util.List;
import org.junit.jupiter.api.Test;

class TimingTest {
  int numExecutions = 53307;
  int numTests = 321;

  // The size of the data is actually much larger than for SonarQube, because
  // SonarQube probably has only 2819 test suite executions that fail.
  @Test
  void testSonarqubeSize() {
    Random r = new Random(0);  // for determinism
    double failureProbability = .01;
    TestFailures tf = TestFailures.random(numExecutions, numTests, failureProbability, r);
    // System.out.println(tf.getSummary());
    // System.out.println(tf);
    long startTime = System.nanoTime();
    List<Integer> prioritized = OrderTests.testIndexesInOrder(tf);
    long elapsed = System.nanoTime() - startTime;
    System.out.println("testSonarqubeSize: elapsed = " + (elapsed / 1000000) / 1000.0);
    System.out.println("tests prioritized: " + prioritized);
  }
}
